main:
  project_name: "nyc_airbnb"  # Make sure this matches
  experiment_name: development
  steps: all
  components_repository: "."  # Use current directory as the base

etl:
  sample: "sample1.csv"
  min_price: 10
  max_price: 350

data_check:
  kl_threshold: 0.2

modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 30
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
